name: gpt-4o-agentic-search-default-agent-advanced-react-prompt-calculator
parallelism: 10

session_runner:
  max_steps: 10
  enable_logging: true

agent:
  model_name: gpt-4o-2024-11-20
  agent_name: default
  system_prompt_name: advanced_react_prompt
  tools:
    - search_pdf
    - calculator
